dcConsData = [
	{name:"노잼.jpg",		keywords:["노잼"],				tags:["닌자"]},
	{name:"닌깔깔.jpg",		keywords:["닌깔깔", "닌하하"],		tags:["닌자"]},
	{name:"닌끼야악.jpg",	keywords:["닌끼야악", "닌꺅"],		tags:["닌자"]},
	{name:"닥쳐.jpg",		keywords:["아닥", "닥쳐"],			tags:["닌자"]},
	{name:"더블피스.jpg",	keywords:["더블피스"],			tags:["닌자"]},
	{name:"도지.png",		keywords:["도지"],				tags:["닌자"]},
	{name:"몰루.jpg",		keywords:["몰루"],				tags:["닌자"]},
	{name:"ㅇㅋ.jpg",		keywords:["ㅇㅋ"],				tags:["닌자"]},
	{name:"안녕.jpg",		keywords:["안녕"],				tags:["닌자"]},
	{name:"웃음.jpg",		keywords:["웃음"],				tags:["닌자"]},
	{name:"칼든쿠로콘.jpg",	keywords:["누칼협", "칼든쿠로콘"],		tags:["닌자"]},
	{name:"으헤헷.jpg",		keywords:["으헤헷"],			tags:["닌자"]},
	{name:"코피.jpg",		keywords:["코피"],				tags:["닌자"]},
	{name:"쿠로구토.jpg",	keywords:["쿠로구토"],			tags:["닌자"]},
	{name:"쿠로놀람.jpg",	keywords:["쿠로놀람"],			tags:["닌자"]},
	{name:"쿠로눈물.jpg",	keywords:["쿠로눈물", "뭣도지"],		tags:["닌자"]},
	{name:"쿠로부끄.jpg",	keywords:["쿠로부끄"],			tags:["닌자"]},
	{name:"쿠로부끄2.jpg",	keywords:["쿠로부끄2"],			tags:["닌자"]},
	{name:"쿠로피곤.jpg",	keywords:["쿠로피곤"],			tags:["닌자"]},
	{name:"쿠로빠큐.jpg",	keywords:["쿠로빠큐"],			tags:["닌자"]},
	{name:"시발아.jpg",		keywords:["시발아", "쿠로분노"],		tags:["닌자"]},
	{name:"쿠로따봉.jpg",	keywords:["쿠로따봉", "따봉"],		tags:["닌자"]},
	{name:"쿠로하트.jpg",	keywords:["쿠로하트", "하트뿅"],		tags:["닌자"]},
	{name:"쿠로핸섬.jpg",	keywords:["쿠로핸섬"],			tags:["닌자"]},
	{name:"파이팅.jpg",		keywords:["파이팅"],			tags:["닌자"]},
	{name:"냥카스.jpg",		keywords:["냥카스"],			tags:["혐"]},
	{name:"어질어질.jpg",	keywords:["어질어질"],			tags:["닌자"]},
	{name:"문풍당당.gif",	keywords:["문풍당당"],			tags:["기타"]},
	{name:"어케했노.gif",	keywords:["어케했노", "어케이겼노"],		tags:["기타"]},
	{name:"어질어질.jpg",	keywords:["어질어질"],			tags:["닌자"]},
	{name:"페바.gif",		keywords:["페바", "종바", "ㅂㅂ"],		tags:["기타"]},
	{name:"펄럭.gif",		keywords:["펄럭"],				tags:["기타"]},
	{name:"쿠로흥분.jpg",	keywords:["쿠로흥분"],			tags:["닌자"]}
];